# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4271dfd57eccf3af7f580705b46260f7c7b959abf5711248a3fed7125828750e477d859203ac76a10fd1cc504b52d28037833fb56b3acebb23f4acef6ba2a54c

test:
  secret_key_base: 5c942062f7d36832d055d6d4feda36fbce0c3e0d4d8fe7486a4f69f6f4b160f7dc645ed6fdb3385b9f23e205c480de618659140e948c510d0fc16fceed0e7211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
